name: Generate MiHomo-Hagezi RuleSets
on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *"
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set ENV variables
        run: |
          echo "RELEASE_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "RELEASE_DATE=$(date +'%A %F %T %Z')" >> $GITHUB_ENV
        shell: bash

      - name: Generate MiHomo mrs rules
        run: |
          MIHOMO_URL=$(curl -s -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/MetaCubeX/mihomo/releases/latest | jq -r '.assets[] | select(.name | test("mihomo-linux-amd64-v.*\\.gz$")) | .browser_download_url' | head -n 1)
          curl -sSLf "$MIHOMO_URL" -o mihomo.gz
          gunzip mihomo.gz
          chmod +x mihomo
          curl -sSLf https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/tif-onlydomains.txt -o Tif.txt
          curl -sSLf https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/ultimate-onlydomains.txt -o TempUltimate.txt
          curl -sSLf https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/pro.plus-onlydomains.txt -o TempProPlus.txt
          curl -sSLf https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/pro-onlydomains.txt -o TempPro.txt
          grep -v '^#' TempUltimate.txt > TempUltimateNew.txt
          sed 's/^/+./' TempUltimateNew.txt > HageziUltimate.txt
          grep -v '^#' TempProPlus.txt > TempProPlusNew.txt
          sed 's/^/+./' TempProPlusNew.txt > HageziProPlus.txt
          grep -v '^#' TempPro.txt > TempProNew.txt
          sed 's/^/+./' TempProNew.txt > HageziPro.txt
          ./mihomo convert-ruleset domain text Tif.txt Tif.mrs
          ./mihomo convert-ruleset domain text HageziUltimate.txt HageziUltimate.mrs
          ./mihomo convert-ruleset domain text HageziProPlus.txt HageziProPlus.mrs
          ./mihomo convert-ruleset domain text HageziPro.txt HageziPro.mrs

      - name: Delete temp files
        run: |
          rm TempUltimateNew.txt
          rm TempUltimate.txt
          rm TempProPlusNew.txt
          rm TempProPlus.txt
          rm TempProNew.txt
          rm TempPro.txt
          rm mihomo

      - name: Move files to publish directory
        run: |
          mkdir -p publish
          cp *.txt ./publish/
          cp *.mrs ./publish/

      - name: Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          files: |
            ./publish/*
      - name: Git push assets to "release" branch
        run: |
          cd publish || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f origin release

      - name: Purge jsdelivr CDN
        run: |
          cd publish || exit 1
          for file in $(ls); do
            curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@release/${file}"
          done
